### ISSUE TITLE
ren q2apro-email-strangulator-lang.php q2apro-email-strangulator-lang-default.php

### ISSUE THREAD

**Issue by amint** [q2apro/q2apro-email-strangulator#1]
Please rename 
q2apro-email-strangulator-lang.php
to
q2apro-email-strangulator-lang-default.php

**Comment by q2apro** [comment]
Thanks. 

https://github.com/q2apro/q2apro-email-strangulator/blob/master/q2apro-email-strangulator-lang-default.php
